---
- name: Copy the PHP configuration file
  ini_file:
    dest: "/etc/php/{{ php_fpm_version }}/fpm/php.ini"
    section: "{{ item.section }}"
    option: "{{ item.option }}"
    value: "{{ item.value }}"
    backup: true
  with_items: "{{ php_fpm_ini }}"
  when: php_fpm_ini|length > 0
  notify:
    - restart php-fpm

- name: Delete the default pool configuration file
  file:
    path: "{{ php_fpm_default_pool }}"
    state: absent

- name: Copy php-fpm configurations
  template:
    src: php-fpm.conf.j2
    dest: "/etc/php/{{ php_fpm_version }}/fpm/php-fpm.conf"
    backup: true
  notify:
    - restart php-fpm

- name: Copy pool configurations
  template:
    src: pool.conf.j2
    dest: "{{ php_fpm_pool }}/app.conf"
    backup: true
  notify:
    - restart php-fpm

- name: Check php-fpm syntax of configuration files
  command: "php-fpm{{ php_fpm_version }} -t"
  register: result
  changed_when: "result.rc != 0"
