---
dependency:
  name: galaxy

driver:
  name: docker

platforms:
  - name: ubuntu-bionic
    image: ubuntu:bionic

provisioner:
  name: ansible
  options:
    diff: true
    v: true
  lint:
    name: ansible-lint
    enabled: false

scenario:
  name: default

verifier:
  name: testinfra
  options:
    disable-pytest-warnings: true
    v: true
  lint:
    name: flake8
